export interface LogoModuleEntry {
  readonly src: string;
  readonly srcDark?: string;
  readonly treatment: string;
  readonly source?: string;
}

/** Renders the typed logo map consumed by `<Stint logos={stintLogos} />`. */
export function renderLogosModule(logos: Readonly<Record<string, LogoModuleEntry>>): string {
  const literal = JSON.stringify(logos, null, 2);
  return `// Generated by stint logos. Keys are experience IDs from stint.config.json.\nimport type { StintLogos } from "@macworks/stint";\n\nexport const stintLogos = ${literal} as const satisfies StintLogos;\n`;
}
